# Generated by Django 5.2.4 on 2025-08-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondaryHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='secondary_hero/')),
                ('heading', models.CharField(max_length=200)),
                ('sub_text', models.TextField()),
            ],
        ),
    ]
