# Generated by Django 5.2.4 on 2025-08-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='carpets/')),
                ('category', models.CharField(choices=[('Wool', 'Wool'), ('Silk', 'Silk'), ('Cotton', 'Cotton')], max_length=100)),
            ],
        ),
    ]
