# Generated by Django 5.2.4 on 2025-08-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='greenwalls/')),
                ('description', models.TextField()),
            ],
        ),
    ]
