# Generated by Django 5.2.4 on 2025-08-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_greenwall'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenwall',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
