# Generated by Django 5.2.4 on 2025-08-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_greenwall_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='sports/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
