# Generated by Django 5.2.4 on 2025-08-05 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_category_artificialplant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialplant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
