# Generated by Django 5.2.4 on 2025-08-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_artificialplant_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='navbar/logo/')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
            ],
        ),
    ]
