# Generated by Django 5.2.4 on 2025-08-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_navbarlogo_navbarmenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('tin', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('business_type', models.CharField(blank=True, choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('others', 'Others')], max_length=50)),
                ('business_address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='business_logos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='business_signatures/')),
            ],
        ),
    ]
