# Generated by Django 5.2.4 on 2025-08-11 13:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heroslide',
            old_name='sub_text',
            new_name='subtext',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(upload_to='hero_slides/'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
