# Generated by Django 5.2.4 on 2025-08-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_sub_text_heroslide_subtext_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarpetProduct',
        ),
        migrations.AlterField(
            model_name='artificialplant',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='artificialplant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='carpet',
            name='name',
        ),
        migrations.AddField(
            model_name='artificialplant',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carpet',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artificialplant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
