# Generated by Django 5.2.4 on 2025-08-12 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_type', models.CharField(choices=[('code39', 'Code 39'), ('code128', 'Code 128'), ('ean13', 'EAN-13'), ('qrcode', 'QR Code')], default='code128', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
