# Generated by Django 5.2.4 on 2025-08-26 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_aboutsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
