# Generated by Django 5.2.4 on 2025-08-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_rename_image_product_main_image_productimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterEmail',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='created_at',
            new_name='subscribed_at',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
